/* Machine-generated by generate_ccode.py.  Do not edit by hand. */

#define SIMPLE_MAXWELL_DERIVS \
    const double dx_Bx = DIFFX(Bx);\
    const double dy_Bx = DIFFY(Bx);\
    const double dz_Bx = DIFFZ(Bx);\
    const double dx_By = DIFFX(By);\
    const double dy_By = DIFFY(By);\
    const double dz_By = DIFFZ(By);\
    const double dx_Bz = DIFFX(Bz);\
    const double dy_Bz = DIFFY(Bz);\
    const double dz_Bz = DIFFZ(Bz);\
    const double dx_Dx = DIFFX(Dx);\
    const double dy_Dx = DIFFY(Dx);\
    const double dz_Dx = DIFFZ(Dx);\
    const double dx_Dy = DIFFX(Dy);\
    const double dy_Dy = DIFFY(Dy);\
    const double dz_Dy = DIFFZ(Dy);\
    const double dx_Dz = DIFFX(Dz);\
    const double dy_Dz = DIFFY(Dz);\
    const double dz_Dz = DIFFZ(Dz);\
    const double dx_PsiB = DIFFX(PsiB);\
    const double dy_PsiB = DIFFY(PsiB);\
    const double dz_PsiB = DIFFZ(PsiB);\
    const double dx_PsiD = DIFFX(PsiD);\
    const double dy_PsiD = DIFFY(PsiD);\
    const double dz_PsiD = DIFFZ(PsiD);\
    const double dx_ieps = DIFFX(ieps);\
    const double dy_ieps = DIFFY(ieps);\
    const double dz_ieps = DIFFZ(ieps);\
    const double dx_imu = DIFFX(imu);\
    const double dy_imu = DIFFY(imu);\
    const double dz_imu = DIFFZ(imu);\
    const double dx_sigma = DIFFX(sigma);\
    const double dy_sigma = DIFFY(sigma);\
    const double dz_sigma = DIFFZ(sigma);

#define SIMPLE_MAXWELL_INTERIOR_DOT \
    SIMPLE_MAXWELL_DERIVS;\
    dotBx[ijk] = dx_PsiB - dy_Dz*ieps[ijk] - dy_ieps*Dz[ijk] + dz_Dy*ieps[ijk] + dz_ieps*Dy[ijk];\
    dotBy[ijk] = dx_Dz*ieps[ijk] + dx_ieps*Dz[ijk] + dy_PsiB - dz_Dx*ieps[ijk] - dz_ieps*Dx[ijk];\
    dotBz[ijk] = -dx_Dy*ieps[ijk] - dx_ieps*Dy[ijk] + dy_Dx*ieps[ijk] + dy_ieps*Dx[ijk] + dz_PsiB;\
    \
    dotDx[ijk] = dx_PsiD + dy_Bz*imu[ijk] + dy_imu*Bz[ijk] - dz_By*imu[ijk] - dz_imu*By[ijk] - four_pi*Dx[ijk]*ieps[ijk]*sigma[ijk];\
    dotDy[ijk] = -dx_Bz*imu[ijk] - dx_imu*Bz[ijk] + dy_PsiD + dz_Bx*imu[ijk] + dz_imu*Bx[ijk] - four_pi*Dy[ijk]*ieps[ijk]*sigma[ijk];\
    dotDz[ijk] = dx_By*imu[ijk] + dx_imu*By[ijk] - dy_Bx*imu[ijk] - dy_imu*Bx[ijk] + dz_PsiD - four_pi*Dz[ijk]*ieps[ijk]*sigma[ijk];\
    \
    dotPsiB[ijk] = dx_Bx + dy_By + dz_Bz - kappa_B*PsiB[ijk];\
    dotPsiD[ijk] = dx_Dx + dy_Dy + dz_Dz - four_pi*rho[ijk] - kappa_D*PsiD[ijk];\
    dotrho[ijk] = -dx_Dx*ieps[ijk]*sigma[ijk] - dx_ieps*Dx[ijk]*sigma[ijk] - dx_sigma*Dx[ijk]*ieps[ijk] - dy_Dy*ieps[ijk]*sigma[ijk] - dy_ieps*Dy[ijk]*sigma[ijk] - dy_sigma*Dy[ijk]*ieps[ijk] - dz_Dz*ieps[ijk]*sigma[ijk] - dz_ieps*Dz[ijk]*sigma[ijk] - dz_sigma*Dz[ijk]*ieps[ijk];

#define APPLY_SAT_LOWER_X(scale_, g_)                                      \
    do {                                                                   \
        const double _s  = (scale_);                                       \
        const double _PP = sqrt(ieps[ijk] / imu[ijk]);                     \
        const double _c  = sqrt(ieps[ijk] * imu[ijk]);                     \
        const double _dBx = Bx[ijk] - (g_).Bx;                             \
        const double _dBy = By[ijk] - (g_).By;                             \
        const double _dBz = Bz[ijk] - (g_).Bz;                             \
        const double _dDx = Dx[ijk] - (g_).Dx;                             \
        const double _dDy = Dy[ijk] - (g_).Dy;                             \
        const double _dDz = Dz[ijk] - (g_).Dz;                             \
        const double _dPB = PsiB[ijk] - (g_).PsiB;                         \
        const double _dPD = PsiD[ijk] - (g_).PsiD;                         \
        dotBx[ijk] -= _s * (0.5*_dBx - 0.5*_dPB);                          \
        dotBy[ijk] -= _s * (_c*(-0.5*_PP*_dDz + 0.5*_dBy));                \
        dotBz[ijk] -= _s * (_c*(0.5*_PP*_dDy + 0.5*_dBz));                 \
        dotDx[ijk] -= _s * (0.5*_dDx - 0.5*_dPD);                          \
        dotDy[ijk] -= _s * (_c*(0.5*_dDy + 0.5*_dBz/_PP));                 \
        dotDz[ijk] -= _s * (_c*(0.5*_dDz - 0.5*_dBy/_PP));                 \
        dotPsiB[ijk] -= _s * (-0.5*_dBx + 0.5*_dPB);                       \
        dotPsiD[ijk] -= _s * (-0.5*_dDx + 0.5*_dPD);                       \
    } while (0)

#define APPLY_SAT_UPPER_X(scale_, g_)                                      \
    do {                                                                   \
        const double _s  = (scale_);                                       \
        const double _PP = sqrt(ieps[ijk] / imu[ijk]);                     \
        const double _c  = sqrt(ieps[ijk] * imu[ijk]);                     \
        const double _dBx = Bx[ijk] - (g_).Bx;                             \
        const double _dBy = By[ijk] - (g_).By;                             \
        const double _dBz = Bz[ijk] - (g_).Bz;                             \
        const double _dDx = Dx[ijk] - (g_).Dx;                             \
        const double _dDy = Dy[ijk] - (g_).Dy;                             \
        const double _dDz = Dz[ijk] - (g_).Dz;                             \
        const double _dPB = PsiB[ijk] - (g_).PsiB;                         \
        const double _dPD = PsiD[ijk] - (g_).PsiD;                         \
        dotBx[ijk] -= _s * (0.5*_dBx + 0.5*_dPB);                          \
        dotBy[ijk] -= _s * (_c*(0.5*_PP*_dDz + 0.5*_dBy));                 \
        dotBz[ijk] -= _s * (_c*(-0.5*_PP*_dDy + 0.5*_dBz));                \
        dotDx[ijk] -= _s * (0.5*_dDx + 0.5*_dPD);                          \
        dotDy[ijk] -= _s * (_c*(0.5*_dDy - 0.5*_dBz/_PP));                 \
        dotDz[ijk] -= _s * (_c*(0.5*_dDz + 0.5*_dBy/_PP));                 \
        dotPsiB[ijk] -= _s * (0.5*_dBx + 0.5*_dPB);                        \
        dotPsiD[ijk] -= _s * (0.5*_dDx + 0.5*_dPD);                        \
    } while (0)

#define APPLY_SAT_LOWER_Y(scale_, g_)                                      \
    do {                                                                   \
        const double _s  = (scale_);                                       \
        const double _PP = sqrt(ieps[ijk] / imu[ijk]);                     \
        const double _c  = sqrt(ieps[ijk] * imu[ijk]);                     \
        const double _dBx = Bx[ijk] - (g_).Bx;                             \
        const double _dBy = By[ijk] - (g_).By;                             \
        const double _dBz = Bz[ijk] - (g_).Bz;                             \
        const double _dDx = Dx[ijk] - (g_).Dx;                             \
        const double _dDy = Dy[ijk] - (g_).Dy;                             \
        const double _dDz = Dz[ijk] - (g_).Dz;                             \
        const double _dPB = PsiB[ijk] - (g_).PsiB;                         \
        const double _dPD = PsiD[ijk] - (g_).PsiD;                         \
        dotBx[ijk] -= _s * (_c*(0.5*_PP*_dDz + 0.5*_dBx));                 \
        dotBy[ijk] -= _s * (0.5*_dBy - 0.5*_dPB);                          \
        dotBz[ijk] -= _s * (_c*(-0.5*_PP*_dDx + 0.5*_dBz));                \
        dotDx[ijk] -= _s * (_c*(0.5*_dDx - 0.5*_dBz/_PP));                 \
        dotDy[ijk] -= _s * (0.5*_dDy - 0.5*_dPD);                          \
        dotDz[ijk] -= _s * (_c*(0.5*_dDz + 0.5*_dBx/_PP));                 \
        dotPsiB[ijk] -= _s * (-0.5*_dBy + 0.5*_dPB);                       \
        dotPsiD[ijk] -= _s * (-0.5*_dDy + 0.5*_dPD);                       \
    } while (0)

#define APPLY_SAT_UPPER_Y(scale_, g_)                                      \
    do {                                                                   \
        const double _s  = (scale_);                                       \
        const double _PP = sqrt(ieps[ijk] / imu[ijk]);                     \
        const double _c  = sqrt(ieps[ijk] * imu[ijk]);                     \
        const double _dBx = Bx[ijk] - (g_).Bx;                             \
        const double _dBy = By[ijk] - (g_).By;                             \
        const double _dBz = Bz[ijk] - (g_).Bz;                             \
        const double _dDx = Dx[ijk] - (g_).Dx;                             \
        const double _dDy = Dy[ijk] - (g_).Dy;                             \
        const double _dDz = Dz[ijk] - (g_).Dz;                             \
        const double _dPB = PsiB[ijk] - (g_).PsiB;                         \
        const double _dPD = PsiD[ijk] - (g_).PsiD;                         \
        dotBx[ijk] -= _s * (_c*(-0.5*_PP*_dDz + 0.5*_dBx));                \
        dotBy[ijk] -= _s * (0.5*_dBy + 0.5*_dPB);                          \
        dotBz[ijk] -= _s * (_c*(0.5*_PP*_dDx + 0.5*_dBz));                 \
        dotDx[ijk] -= _s * (_c*(0.5*_dDx + 0.5*_dBz/_PP));                 \
        dotDy[ijk] -= _s * (0.5*_dDy + 0.5*_dPD);                          \
        dotDz[ijk] -= _s * (_c*(0.5*_dDz - 0.5*_dBx/_PP));                 \
        dotPsiB[ijk] -= _s * (0.5*_dBy + 0.5*_dPB);                        \
        dotPsiD[ijk] -= _s * (0.5*_dDy + 0.5*_dPD);                        \
    } while (0)

#define APPLY_SAT_LOWER_Z(scale_, g_)                                      \
    do {                                                                   \
        const double _s  = (scale_);                                       \
        const double _PP = sqrt(ieps[ijk] / imu[ijk]);                     \
        const double _c  = sqrt(ieps[ijk] * imu[ijk]);                     \
        const double _dBx = Bx[ijk] - (g_).Bx;                             \
        const double _dBy = By[ijk] - (g_).By;                             \
        const double _dBz = Bz[ijk] - (g_).Bz;                             \
        const double _dDx = Dx[ijk] - (g_).Dx;                             \
        const double _dDy = Dy[ijk] - (g_).Dy;                             \
        const double _dDz = Dz[ijk] - (g_).Dz;                             \
        const double _dPB = PsiB[ijk] - (g_).PsiB;                         \
        const double _dPD = PsiD[ijk] - (g_).PsiD;                         \
        dotBx[ijk] -= _s * (_c*(-0.5*_PP*_dDy + 0.5*_dBx));                \
        dotBy[ijk] -= _s * (_c*(0.5*_PP*_dDx + 0.5*_dBy));                 \
        dotBz[ijk] -= _s * (0.5*_dBz - 0.5*_dPB);                          \
        dotDx[ijk] -= _s * (_c*(0.5*_dDx + 0.5*_dBy/_PP));                 \
        dotDy[ijk] -= _s * (_c*(0.5*_dDy - 0.5*_dBx/_PP));                 \
        dotDz[ijk] -= _s * (0.5*_dDz - 0.5*_dPD);                          \
        dotPsiB[ijk] -= _s * (-0.5*_dBz + 0.5*_dPB);                       \
        dotPsiD[ijk] -= _s * (-0.5*_dDz + 0.5*_dPD);                       \
    } while (0)

#define APPLY_SAT_UPPER_Z(scale_, g_)                                      \
    do {                                                                   \
        const double _s  = (scale_);                                       \
        const double _PP = sqrt(ieps[ijk] / imu[ijk]);                     \
        const double _c  = sqrt(ieps[ijk] * imu[ijk]);                     \
        const double _dBx = Bx[ijk] - (g_).Bx;                             \
        const double _dBy = By[ijk] - (g_).By;                             \
        const double _dBz = Bz[ijk] - (g_).Bz;                             \
        const double _dDx = Dx[ijk] - (g_).Dx;                             \
        const double _dDy = Dy[ijk] - (g_).Dy;                             \
        const double _dDz = Dz[ijk] - (g_).Dz;                             \
        const double _dPB = PsiB[ijk] - (g_).PsiB;                         \
        const double _dPD = PsiD[ijk] - (g_).PsiD;                         \
        dotBx[ijk] -= _s * (_c*(0.5*_PP*_dDy + 0.5*_dBx));                 \
        dotBy[ijk] -= _s * (_c*(-0.5*_PP*_dDx + 0.5*_dBy));                \
        dotBz[ijk] -= _s * (0.5*_dBz + 0.5*_dPB);                          \
        dotDx[ijk] -= _s * (_c*(0.5*_dDx - 0.5*_dBy/_PP));                 \
        dotDy[ijk] -= _s * (_c*(0.5*_dDy + 0.5*_dBx/_PP));                 \
        dotDz[ijk] -= _s * (0.5*_dDz + 0.5*_dPD);                          \
        dotPsiB[ijk] -= _s * (0.5*_dBz + 0.5*_dPB);                        \
        dotPsiD[ijk] -= _s * (0.5*_dDz + 0.5*_dPD);                        \
    } while (0)

